defaults:
  - autoencoder: stable_vae
  - backbone: audio_udit

_target_: models.diffusion.AudioDiffusion
content_encoder:
  _target_: models.content_encoder.caption_encoder.ContentEncoder
  text_encoder:
    _target_: models.content_encoder.text_encoder.T5TextEncoder
    model_name: "/mnt/petrelfs/zhengzihao/cache/google-flan-t5-large"

frame_resolution: 0.005
noise_scheduler_name: "/mnt/petrelfs/zhengzihao/cache/stabilityai-stable-diffusion-2-1"
snr_gamma: 5.0
classifier_free_guidance: True
cfg_drop_ratio: 0.2